const MASTER_ITEMS = [
    { name: "Apple", emoji: "🍎", cat: "Fruits" },
    { name: "Banana", emoji: "🍌", cat: "Fruits" },
    { name: "Mango", emoji: "🥭", cat: "Fruits" },
    { name: "Orange", emoji: "🍊", cat: "Fruits" },
    { name: "Grapes", emoji: "🍇", cat: "Fruits" },
    { name: "Potato", emoji: "🥔", cat: "Vegetables" },
    { name: "Tomato", emoji: "🍅", cat: "Vegetables" },
    { name: "Onion", emoji: "🧅", cat: "Vegetables" },
    { name: "Spinach", emoji: "🥬", cat: "Vegetables" },
    { name: "Rice", emoji: "🍚", cat: "Kitchen" },
    { name: "Flour", emoji: "🌾", cat: "Kitchen" },
    { name: "Sugar", emoji: "🍬", cat: "Kitchen" },
    { name: "Milk", emoji: "🥛", cat: "Dairy" },
    { name: "Butter", emoji: "🧈", cat: "Dairy" },
    { name: "Cheese", emoji: "🧀", cat: "Dairy" },
    { name: "Soft Drink", emoji: "🥤", cat: "Drinks" },
    { name: "Chips", emoji: "🍟", cat: "Snacks" },
    { name: "Soap", emoji: "🧼", cat: "Bathroom" },
    { name: "Shampoo", emoji: "🧴", cat: "Bathroom" },
    { name: "Lipstick", emoji: "💄", cat: "Girls Essentials" },
    { name: "Sanitary Pads", emoji: "🩸", cat: "Girls Essentials" },
    { name: "Detergent", emoji: "🧼", cat: "Cleaning" }
];